# Structures de Controle

Les structures de contrôle sont des instructions qui permettent de contrôler le flux d'exécution d'un programme. Elles sont essentielles pour la programmation car elles permettent de réaliser des tâches complexes, telles que la prise de décision, la répétition et la sélection de données. Il existe 3 principales **structures de controle** pour créer des algorithmes.
- Les alternatives **If / Else**
- Les boucles **For**
- Les boucles **While**

## 1. Alternatives If / Else :
 Permettent de conditionner l'exécution d'un bloc de code en fonction de la valeur d'une condition.

In [ ]:
def test_du_signe(valeur):
  if valeur < 0:
    print('négatif')
  elif valeur == 0:
    print('nul')
  else:
    print('positif')

In [ ]:
test_du_signe(-2)

négatif


**Note importante : Une condition est respectée si et seulement si elle correspond au résultat **booléen True**.**

Cela permet de développer des algorithmes avec des mélanges d'opéations Logiques et d'opérations de comparaisons. Par exemple : *si il fait beau et qu'il faut chaud, alors j'irai me baigner*

In [ ]:
def aller_se_baigner(fait_beau, fait_chaud):
    if fait_beau and fait_chaud:
        print("J'irai me baigner !")
    else:
        print("Je ne vais pas me baigner.")

# Appelons la fonction
aller_se_baigner(fait_beau=True, fait_chaud=True)


**EXEMPLE  1**

Écrivez un programme qui demande à l'utilisateur de saisir un nombre. Si le nombre est pair, le programme doit afficher la chaîne "Le nombre est pair". Sinon, le programme doit afficher la chaîne "Le nombre est impair"

In [ ]:
# Demandons à l'utilisateur de saisir un nombre
nombre = input("Saisissez un nombre : ")

# Convertissons le nombre en entier
nombre = int(nombre)

# Testons si le nombre est pair
if nombre % 2 == 0:
    # Si oui, affichons le message approprié
    print("Le nombre est pair")
else:
    # Sinon, affichons le message approprié
    print("Le nombre est impair")

## 2. Boucle For
Une boucle for permet de créer des algorithmes itératifs (qui effectuent une certaine tache plusieurs fois de suite). Pour ca, la boucle parcourt tous les éléments d'un objet dit **itérable**. Il peut s'agir d'une liste, d'un dictionnaire, d'un range, d'un tableau numpy, ou de bien d'autres objets...

In [ ]:
for i in range(0, 10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
# on peut s'amuser a combiner cette boucle avec notre fonction de tout a l'heure.
for i in range(-10, 10, 2):
  print(i)
  test_du_signe(i)

-10
négatif
-8
négatif
-6
négatif
-4
négatif
-2
négatif
0
nul
2
positif
4
positif
6
positif
8
positif


**Exemple 2**

Écrivez un programme Python qui calcule la somme des nombres de 1 à 10.

In [ ]:
# Initialisons la variable somme
somme = 0

# Pour chaque nombre de 1 à 10, ajoutons-le à la somme
for i in range(1, 11):
    somme += i

# Affichons la somme
print(somme)

55


## 3. Boucle While
Une boucle While permet d'effectuer en boucle une action, tant que la condition d'execution est validée (tant que la condition est **True**)

In [ ]:
x = 0
while x < 10:
  print(x)
  x += 1 # incrémente x de 1 (équivalent de x = x+1)

0
1
2
3
4
5
6
7
8
9


**Exemple 3**

Écrivez un programme qui demande à l'utilisateur de saisir un nombre. Le programme doit ensuite afficher tous les nombres pairs inférieurs ou égaux au nombre saisi.

In [ ]:
# Demandons à l'utilisateur de saisir un nombre
nombre = input("Saisissez un nombre : ")

# Convertissons le nombre en entier
nombre = int(nombre)

# Initialisons la variable compteur
compteur = 0

# Tant que le compteur est inférieur ou égal au nombre saisi, continuons
while compteur <= nombre:
    # Si le compteur est pair, affichons-le
    if compteur % 2 == 0:
        print(compteur)
    # Incrémentons le compteur
    compteur += 1

**Numpy : Tableau ndarray**

In [ ]:
import numpy as np

**Création des données avec numpy**


Créer un numpy array avec une liste/liste de liste (matrice)

In [ ]:
# Création à partir d'une liste
liste = [1, 2, 3, 4, 5, 6, 7, 8, 9]  # Définition de la liste d'élément
array_liste = np.array(liste)
print(array_liste)  # affiche le numpy array

[1 2 3 4 5 6 7 8 9]


In [ ]:
# Création à partir d'une matrice

In [ ]:
# Création d'un numpy array à partir d'une liste de listes (matrice)
matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10,  11, 12]]
array_matrice = np.array(matrice)
print(array_matrice)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Créer un numpy array à partir des fonctions intégrées**


In [ ]:
#Créer un numpy array à partir de la fonction zeros
array_zeros = np.zeros((4,4))
print(array_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Créer un numpy array à partir de la fonction ones
array_ones = np.ones((3,2))
print(array_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Créer un numpy array avec la fonction eye
array_eye = np.eye(3)#Pour créer la matrice identité
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Créer un numpy array avec la fonction arange
array_arange = np.arange(0, 11)
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Créer un numpy array avec la fonction linspace
#entre deux valeurs données avec un nombre de points donné
array_linspace = np.linspace(0, 1, 20)#Très utile pour les graphiques
array_linspace

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# Créer un numpy array de valeurs aléatoires avec la fonction random
#Utile pour initialiser les poids dans les réseaux de neurones, générer des données d'apprentissage synthétiques
array_random = np.random.random((5,4))
print(array_random)

[[0.51912264 0.01048643 0.94342975 0.85742174]
 [0.7928877  0.58589245 0.01582001 0.87382869]
 [0.63833588 0.94296402 0.88759917 0.84538343]
 [0.31415968 0.48390603 0.69187053 0.55264551]
 [0.0394426  0.19261155 0.62026706 0.25602988]]


**Fonctions mathématiques et statistiques avec Numpy**

In [ ]:
#Fonction mathématiques basiques
array1=array_liste
array_sum = np.sum(array1)
print (array_sum )
array_mean = np.mean(array1)
print (array_mean )
array_std = np.std(array1)
print (array_std )
array_min = np.min(array1)
print (array_min )
array_max = np.max(array1)
print (array_max)
array_sqrt = np.sqrt(array1)
print (array_sqrt)
array_abs = np.abs(array1)
print (array_abs)
array_power = np.power(array1, 2)
print (array_power)
array_exp = np.exp(array1)
print (array_exp)
array_log = np.log(np.abs(array1))
print (array_log)
array_sin = np.sin(array1)
print (array_sin)
array_median = np.median(array1)
print (array_median)


36
4.5
2.29128784747792
1
8
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712]
[1 2 3 4 5 6 7 8]
[ 1  4  9 16 25 36 49 64]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825]
4.5


**Manipulation des matrices avec Numpy**

In [ ]:
# Produit matriciel
matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
produit_matriciel = np.dot(matrice, matrice)
print(produit_matriciel)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [ ]:
# Transposée
transposee = np.transpose(matrice)
print(transposee)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#Déterminant
determinant=np.linalg.det(array_eye)
print(determinant)

1.0


In [ ]:
# Inversion (pour les matrices carrées non singulières)
inverse = np.linalg.inv(array_eye)
print(inverse)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Déterminant
determinant=np.linalg.det(array_eye)
print(determinant)

**Accéder aux éléments, sélectionner, modifier et mettre à jour un numpy array**

In [ ]:
# Accès aux éléments
array1 = np.array([1,2,3,4,5])
premier_element = array1[0]
print(premier_element)

1


In [ ]:
array1[2]

3

In [ ]:
# Modification d'un élément
array1[0] = 15
print(array1)

[15  2  3  4  5]


In [ ]:
# Sélection des éléments qui respectent une condition
elements_respectant_condition = array1[array1 > 2]
elements_respectant_condition

array([15,  3,  4,  5])

In [ ]:
condition = array1 > 3
condition
indices = np.where(array1 > 3)
indices

(array([0, 3, 4]),)

In [ ]:
# Mise à jour d'un numpy array
array1[condition] = 0
print(array1)


In [ ]:
# Utilisation de where
array = np.array([-1, 0, 1, 2, 3])

resultat = np.where(array > 0, 1, 0)

print(resultat)


In [ ]:
# Utilisation de where
array = np.array([1, 2, 3, 4, 5])

resultat = np.where(array % 2 == 0, "pair", "impair")

print(resultat)


In [ ]:
# Utilisation de sort
array = np.array([5, 2, 1, 3, 4])

resultat = np.sort(array)

print(resultat)


In [ ]:
# Utilisation de sort
array = np.array([[1, 2], [3, 4], [5, 6]])

resultat = np.sort(array, axis=0)

print(resultat)


In [ ]:
## Utilisation de argsort
array = np.array([5, 2, 1, 3, 4])

resultat = np.argsort(array)

print(resultat)


In [ ]:
#  Slicing et indexation avancée
arrayT = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Indexation simple

premiere_ligne = arrayT[0, :]
print(premiere_ligne)


deuxieme_colonne = arrayT[:, 1]
print(deuxieme_colonne)



array([1, 2, 3])

In [ ]:
# Slicing

deux_premieres_lignes = arrayT[:2, :]
print(deux_premieres_lignes)


deux_dernieres_lignes = arrayT[1:, :]
print(deux_dernieres_lignes)


deux_premieres_colonnes = arrayT[:, :2]
print(deux_premieres_colonnes)


deux_dernieres_colonnes = arrayT[:, 1:]
print(deux_dernieres_colonnes)

In [ ]:

# Indexation avancée

elements_premiere_ligne_a_partir_du_troisieme = arrayT[0, 2:]
print(elements_premiere_ligne_a_partir_du_troisieme)


elements_deuxieme_colonne_a_partir_du_quatrieme = arrayT[:, 3:]
print(elements_deuxieme_colonne_a_partir_du_quatrieme)


diagonale = arrayT.diagonal()
print(diagonale)


sous_matrice = arrayT[1:3, 1:3]
print(sous_matrice)

In [ ]:
# Opérations élémentaires et diffusion (broadcasting)
array7 = np.array([1, 2, 3])
array8 = np.array([4, 5, 6])


# Addition élémentaire
array_addition = array7 + array8
array_addition

In [ ]:
# Multiplication élémentaire
array_multiplication = array7 * array8
array_multiplication

In [ ]:
# Diffusion (broadcasting)
array9 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array10 = np.array([1, 2, 3])
array9+array10

**Redimensionnement, append, type de données taille etc**

In [ ]:
#Redimensionné le numpy array
array3 = np.arange(9)
array3_redimensionne = array3.reshape((3, 3))
print(array3_redimensionne)

In [ ]:
array3 = np.arange(9)
array3

In [ ]:
#Ajouter des éléments dans un numpy array
array1_allonge = np.append(array1, [6, 7, 8])
print(array1_allonge)

In [ ]:
#Connaitre les caractéristiques d'un numpy array
array_matrice.shape

In [ ]:
#Connaitre le type de l'objet
type(array_matrice)

In [ ]:
#Connaitre le type des éléments
array1.dtype